# Generated by Django 6.0 on 2025-12-08 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва (напр. Місячний)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Тривалість (днів)')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата закінчення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptiontype')),
            ],
        ),
    ]
