# Generated by Django 6.0 on 2025-12-08 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clientstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Досвід / Про себе'),
        ),
        migrations.CreateModel(
            name='TrainerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва сертифікату')),
                ('issued_by', models.CharField(max_length=100, verbose_name='Ким виданий')),
                ('date_issued', models.DateField(verbose_name='Дата видачі')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
