# Generated by Django 6.0 on 2025-12-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва тренування')),
                ('start_time', models.DateTimeField(verbose_name='Початок')),
                ('end_time', models.DateTimeField(verbose_name='Кінець')),
                ('capacity', models.PositiveIntegerField(default=20, verbose_name='Місць')),
            ],
        ),
    ]
