# Generated by Django 6.0 on 2025-12-08 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='rpe',
            field=models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='RPE(Оцінка складності)'),
        ),
    ]
