# Generated by Django 6.0 on 2025-12-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_record_rpe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Назва вправи')),
                ('description', models.TextField(blank=True, verbose_name='Опис / Техніка')),
            ],
            options={
                'verbose_name': 'Вправа',
                'verbose_name_plural': 'Довідник вправ',
            },
        ),
    ]
